apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo error && echo helloworld && echo nirmata && echo erroragain && echo catchthisERROR && sleep 36000']
